"""Brain cloud exporter: the fixed neuron sample shared by the brain server (spike bits) and the
lens (Spectacles/.../BrainCloudData.ts), plus per-neuron GROUP bits for the board's hover
highlight (11.09 the user: "hover a bar -> that branch of the brain lights up").

    cd "${CYBERFLY_RUNTIME:-$HOME/cyberfly_runtime}/fly-wirehead" && uv run python "<repo>/brain/export_cloud.py"

Keeps the existing 16,000-neuron sample (same colours, same axes) and swaps in every command
cell the board reads (DNa02, escape DNs, DNpe007, MN9, PPL101) in place of random optic-lobe
cells, so hovering those rows lights real neurons. N stays 16,000: 4 verts/neuron must stay
under 65,536 (UInt16 indices) and 16,000 fits the 128x128 activity texture.
Restart the brain server afterwards (it reads the sample at start).
"""

import json
import os
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "brain_server"))
RUNTIME = Path(os.environ.get("CYBERFLY_RUNTIME", Path.home() / "cyberfly_runtime")).expanduser()
os.environ.setdefault("FLYWIREHEAD_DATA", str(RUNTIME / "fly-wirehead/data"))

from channels import index_readouts, index_regions  # noqa: E402

RES = ROOT / "brain/results"
TS = ROOT / "Spectacles/Assets/Scripts/Fly/BrainCloudData.ts"
# bit order == FlyBoard NEURAL row keys
GROUPS = ["optic", "central", "mushroom", "sensory", "descending", "vnc",
          "DNa02_L", "DNa02_R", "escape", "stop", "feed", "stress"]
COMMANDS = GROUPS[6:]


def ts_array(text, name, dtype):
    body = text.split(f"export const {name} = new ")[1]
    return np.array(json.loads(body[body.index("(") + 1: body.index(")")]), dtype)


def main():
    from flywirehead.neural.common import annotations

    pc = np.load(RES / "pointcloud.npz")
    ids, sc_code, names, xyz = pc["ids"], pc["superclass"], pc["superclass_names"], pc["xyz"]
    a = annotations(ids)
    members = index_regions(names[sc_code], a.type.fillna("").to_numpy())
    ro = index_readouts(a)
    for k in ("DNa02_L", "DNa02_R", "stop", "feed", "stress"):
        members[k] = ro[k]
    members["escape"] = np.union1d(ro["esc_L"], ro["esc_R"])

    old = np.load(RES / "cloud_subset.npz")
    text = TS.read_text()
    # the lens file must match the old sample exactly (identity axes) before we touch it
    q_old = np.round(old["xyz"] * 32767).astype(np.int64).ravel()
    assert np.abs(ts_array(text, "CLOUD_XYZ", np.int64) - q_old).max() <= 1, "BrainCloudData.ts != cloud_subset.npz"
    hue_of = {}
    for code, h in zip(old["superclass"], ts_array(text, "CLOUD_HUE", np.int64)):
        hue_of.setdefault(int(code), int(h))

    idx = old["idx"].astype(np.int64)
    n = len(idx)
    must = np.unique(np.concatenate([members[k] for k in COMMANDS]))
    missing = np.setdiff1d(must, idx)
    if len(missing):
        pool = np.flatnonzero(np.isin(idx, members["optic"]) & ~np.isin(idx, must))
        drop = np.random.default_rng(11).choice(pool, size=len(missing), replace=False)
        idx = np.sort(np.concatenate([np.delete(idx, drop), missing]))
    assert len(idx) == n == len(np.unique(idx)) and n * 4 < 65536 and n <= 128 * 128

    bits = np.zeros(n, np.uint16)
    for b, k in enumerate(GROUPS):
        bits[np.isin(idx, members[k])] |= 1 << b
    hue = np.array([hue_of.get(int(c), 0) for c in sc_code[idx]], np.uint8)
    q = np.round(xyz[idx] * 32767).astype(np.int16)

    np.savez_compressed(RES / "cloud_subset_prev.npz", **{k: old[k] for k in old.files})
    np.savez_compressed(RES / "cloud_subset.npz", idx=idx.astype(np.int32), xyz=xyz[idx],
                        superclass=sc_code[idx], superclass_names=names, group=bits)
    lines = [
        "// GENERATED by brain/export_cloud.py from brain/results/cloud_subset.npz — do not edit.",
        f"// {n:,} MaleCNS neurons (same sample + order the brain server streams as spike bits).",
        "// XYZ: int16 quantised from [-1,1] (x right, y up, z anterior-posterior); HUE: superclass colour 0..255.",
        "// GROUP: bit b set = the neuron belongs to CLOUD_GROUP_KEYS[b] (board row keys, hover highlight).",
        f"export const CLOUD_N = {n}",
        "export const CLOUD_XYZ = new Int16Array([" + ",".join(map(str, q.ravel().tolist())) + "])",
        "export const CLOUD_HUE = new Uint8Array([" + ",".join(map(str, hue.tolist())) + "])",
        "export const CLOUD_CLASSES = " + json.dumps([str(s) for s in names]),
        "export const CLOUD_GROUP_KEYS = " + json.dumps(GROUPS),
        "export const CLOUD_GROUP = new Uint16Array([" + ",".join(map(str, bits.tolist())) + "])",
        "",
    ]
    TS.write_text("\n".join(lines))
    print(f"swapped in {len(missing)} command cells; sample {n}")
    for b, k in enumerate(GROUPS):
        print(f"  {k:11s} {int(((bits >> b) & 1).sum()):6d} in cloud / {len(members[k]):6d} in brain")


if __name__ == "__main__":
    main()
