#!/bin/bash
# GLSL -> SPIR-V for the six entry points of src/gpu/brain.comp, embedded as C arrays in
# src/gpu/brain_spv.h (committed: the device build needs no shader compiler). Vulkan 1.1 target.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$HERE/../src/gpu/brain.comp"
OUT="$HERE/../src/gpu/brain_spv.h"
GLSLC="${GLSLC:-glslc}"
TMP="$(mktemp -d)"
{
  echo "// generated by tools/build_spv.sh from brain.comp; do not edit"
  echo "#pragma once"
  echo "#include <cstdint>"
  echo "#include <cstddef>"
  for K in BEGIN TICKA TICKB END BLKSORT RANK; do
    "$GLSLC" -fshader-stage=compute --target-env=vulkan1.1 -O -DK_$K "$SRC" -o "$TMP/$K.spv"
    spirv-val --target-env vulkan1.1 "$TMP/$K.spv"
    echo "static const uint32_t SPV_$K[] = {"
    python3 - "$TMP/$K.spv" <<'EOF'
import struct, sys
d = open(sys.argv[1], "rb").read()
w = struct.unpack("<%dI" % (len(d) // 4), d)
for i in range(0, len(w), 12):
    print("  " + ", ".join("0x%08x" % x for x in w[i:i + 12]) + ",")
EOF
    echo "};"
    echo "static const size_t SPV_${K}_BYTES = sizeof(SPV_$K);"
  done
} > "$OUT"
rm -rf "$TMP"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
