"""Build the board's MSDF+SDF font atlases from the project's own fonts.

    python3 tools/text/build_atlas.py

Why: the board drew every label as its own Component.Text — 67 draw calls of the ~90 in view on
device, and every `.text` write re-tessellated that text's mesh (12.09 recording pass, ADR 39/40).
`TextBatch` draws all of them from one mesh instead, which needs a glyph atlas.

Output (both committed):
    Spectacles-5.23/Assets/Fly/UI/Fonts/BoardUi.png    + Scripts/Fly/BoardUiFontData.ts
    Spectacles-5.23/Assets/Fly/UI/Fonts/BoardMono.png  + Scripts/Fly/BoardMonoFontData.ts
    (CYBERFLY_PROJECT=Spectacles-5.15 writes into the 5.15 project instead)

RGB carries the 3-channel MSDF (sharp body via the median trick), A carries a plain SDF (rounded
outline). The metadata goes in as a TS module because Lens Studio has no runtime JSON loader; its
base name must differ from the PNG's or LS silently breaks `require()` (sdf-font-atlas skill).

Needs `npm i -g msdf-bmfont-xml`, Pillow. ASCII 0x20-0x7E only: the board has no other glyphs.
"""
import json
import os
import shutil
import subprocess
import sys
import tempfile

from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
# the 5.23 project is where a change lands first; the 5.15 copy takes the same files (RUNBOOK: copy, never merge)
PROJECT = os.environ.get("CYBERFLY_PROJECT", "Spectacles-5.23")
FONTS = os.path.join(ROOT, PROJECT, "Assets/Fly/UI/Fonts")
SCRIPTS = os.path.join(ROOT, PROJECT, "Assets/Scripts/Fly")
# (source ttf, output name) — the on-screen look must not change, so these are the board's own faces
JOBS = [("ChakraPetch-SemiBold", "BoardUi"), ("ShareTechMono-Regular", "BoardMono")]
SIZE = 96  # glyph px; the board's caps are ~0.7 cm at ~1 m, so 96 is already generous
RANGE = 16  # SDF distance range; padding must be >= RANGE/2 or glyph fields clip into each other
PAD = 8


def main():
    work = tempfile.mkdtemp(prefix="boardatlas_")
    charset = os.path.join(work, "charset.txt")
    with open(charset, "w", encoding="utf-8") as f:
        f.write("".join(chr(c) for c in range(0x20, 0x7F)))

    for src, out in JOBS:
        d = os.path.join(work, out)
        os.makedirs(d, exist_ok=True)
        for kind in ("msdf", "sdf"):
            cmd = ["msdf-bmfont", "-f", "json", "-t", kind, "-s", str(SIZE), "-m", "1024,1024",
                   "-p", str(PAD), "-r", str(RANGE), "-i", charset, "-o", f"{out}_{kind}",
                   os.path.join(FONTS, src + ".ttf")]
            subprocess.run(cmd, cwd=d, check=True, capture_output=True)
        # the tool writes <FontName>.json (NOT <prefix>.json) next to the pngs
        msdf = Image.open(os.path.join(d, out + "_msdf.png")).convert("RGBA")
        sdf = Image.open(os.path.join(d, out + "_sdf.png")).convert("RGBA")
        assert msdf.size == sdf.size, (out, msdf.size, sdf.size)
        r, g, b, _ = msdf.split()
        a, _, _, _ = sdf.split()
        png = os.path.join(FONTS, out + ".png")
        Image.merge("RGBA", (r, g, b, a)).save(png, optimize=True)

        meta = json.load(open(os.path.join(d, src + ".json")))
        ts = os.path.join(SCRIPTS, out + "FontData.ts")
        with open(ts, "w") as f:
            f.write("// GENERATED by tools/text/build_atlas.py - MSDF+SDF metadata for " + out + ".png. Do not edit.\n")
            f.write("const data = " + json.dumps(meta, separators=(",", ":")) + "\n")
            f.write("export = data\n")
        # self-check: the atlas must not be blank and every requested glyph must be in it
        assert len(meta["chars"]) >= 90, f"{out}: only {len(meta['chars'])} glyphs"
        assert msdf.getbbox() is not None, f"{out}: blank atlas"
        print(f"{out}: {msdf.size[0]}x{msdf.size[1]}  {len(meta['chars'])} glyphs  "
              f"range {meta['distanceField']['distanceRange']}  {os.path.getsize(png) // 1024} KB")
    shutil.rmtree(work, ignore_errors=True)


if __name__ == "__main__":
    sys.exit(main())
